In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils

Using TensorFlow backend.


In [2]:
text=(open('sonnets.txt').read())
text=text.lower()

In [3]:
characters = sorted(list(set(text)))
print(characters)

num_to_char = {n:char for n, char in enumerate(characters)}
print('num_to_char:', num_to_char)

char_to_num = {char:n for n, char in enumerate(characters)}
print('char_to_num:', char_to_num)

['\n', ' ', '!', '"', '#', '$', '%', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', '@', '[', ']', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']
num_to_char: {0: '\n', 1: ' ', 2: '!', 3: '"', 4: '#', 5: '$', 6: '%', 7: "'", 8: '(', 9: ')', 10: '*', 11: ',', 12: '-', 13: '.', 14: '/', 15: '0', 16: '1', 17: '2', 18: '3', 19: '4', 20: '5', 21: '6', 22: '7', 23: '8', 24: '9', 25: ':', 26: ';', 27: '?', 28: '@', 29: '[', 30: ']', 31: 'a', 32: 'b', 33: 'c', 34: 'd', 35: 'e', 36: 'f', 37: 'g', 38: 'h', 39: 'i', 40: 'j', 41: 'k', 42: 'l', 43: 'm', 44: 'n', 45: 'o', 46: 'p', 47: 'q', 48: 'r', 49: 's', 50: 't', 51: 'u', 52: 'v', 53: 'w', 54: 'x', 55: 'y', 56: 'z', 57: '\ufeff'}
char_to_num: {'\n': 0, ' ': 1, '!': 2, '"': 3, '#': 4, '$': 5, '%': 6, "'": 7, '(': 8, ')': 9, '*': 10, ',': 11, '-': 12, '.': 13, '/': 14, '0': 15, '1': 16, '2': 17, '3':

In [4]:
X = []
Y = []

length = len(text)
print(length)

seq_length = 100
for i in range(0, length-seq_length, 1):
    sequence = text[i:i + seq_length]
    label = text[i + seq_length]
    X.append([char_to_num[char] for char in sequence])
    Y.append(char_to_num[label])

119749


In [5]:
X_modified = np.reshape(X, (len(X), seq_length, 1))
X_modified = X_modified / float(len(characters))
Y_modified = np_utils.to_categorical(Y)

In [6]:
print(X_modified)
print(Y_modified)

[[[0.98275862]
  [0.86206897]
  [0.65517241]
  ...
  [0.86206897]
  [0.65517241]
  [0.60344828]]

 [[0.86206897]
  [0.65517241]
  [0.60344828]
  ...
  [0.65517241]
  [0.60344828]
  [0.01724138]]

 [[0.65517241]
  [0.60344828]
  [0.01724138]
  ...
  [0.60344828]
  [0.01724138]
  [0.87931034]]

 ...

 [[0.86206897]
  [0.77586207]
  [0.01724138]
  ...
  [0.77586207]
  [0.77586207]
  [0.70689655]]

 [[0.77586207]
  [0.01724138]
  [0.65517241]
  ...
  [0.77586207]
  [0.70689655]
  [0.84482759]]

 [[0.01724138]
  [0.65517241]
  [0.60344828]
  ...
  [0.70689655]
  [0.84482759]
  [0.22413793]]]
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [14]:
model = Sequential()
model.add(LSTM(400, input_shape=(X_modified.shape[1], X_modified.shape[2]), return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(400))
model.add(Dropout(0.2))
model.add(Dense(Y_modified.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')

In [15]:
model.fit(X_modified, Y_modified, epochs=1, batch_size=100)

model.save_weights('Users/mark.hustad/Desktop/deep-learning')

Instructions for updating:
Use tf.cast instead.
Epoch 1/1
  8500/119649 [=>............................] - ETA: 59:09 - loss: 3.1053

KeyboardInterrupt: 

In [11]:
string_mapped = X[99]
full_string = [num_to_char[value] for value in string_mapped]
# generating characters
for i in range(400):
    x = np.reshape(string_mapped,(1,len(string_mapped), 1))
    x = x / float(len(characters))
    pred_index = np.argmax(model.predict(x, verbose=0))
    seq = [num_to_char[value] for value in string_mapped]
    string_mapped.append(pred_index)
    string_mapped = string_mapped[1:len(string_mapped)]

ValueError: Error when checking input: expected lstm_1_input to have shape (100, 1) but got array with shape (101, 1)

In [9]:
print(string_mapped)

[51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51]


In [ ]:
txt=""
for char in full_string:
    txt = txt+char
txt